require "baked_file_system"

module IcingaPagerduty
  # The third-party notices the released binary has to carry, embedded at
  # compile time. A statically linked binary contains its dependencies' code, so
  # it has to contain their notices too; harvesting them at build time rather
  # than maintaining a NOTICE file by hand keeps the artifact honest as the
  # dependency list moves.
  #
  # The folder is generated by scripts/harvest-licenses.sh — `mise dev:licenses`,
  # or the `licenses` target of Makefile.release inside the Alpine builder — and
  # is gitignored. It has to exist before this file is compiled, which is why
  # every task that compiles declares that script as a dependency, `dev:docs`
  # included: `crystal doc` runs the macros too.
  module Licenses
    extend BakedFileSystem

    bake_folder "../../licenses"
  end
end
